name: f1-flask-site
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    run_command: gunicorn app:app
    build_command: pip install -r requirements.txt
    environment_slug: python
    instance_size_slug: basic-xxs
    routes:
      - path: /
